---
- hosts: localhost

  pre_tasks:
    - name: Run the equivalent of "pacman -Syu"
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

  roles:
    - role: users
      tags: users

    - role: grub
      tags: grub

    - role: network
      tags: network

    - role: terminal
      tags: terminal

    - role: desktop
      tags: desktop

    - role: text_editor
      tags: text_editor

    - role: browser
      tags: browser

    - role: utilities
      tags: utilities

    - role: communication
      tags: communication

    - role: dev
      tags: dev
