---
- name: Install power managing service
  pacman:
    name: powerdevil
    state: present
  become: yes

- name: Install integration with power profiles
  pacman:
    name: power-profiles-daemon
    state: present
  become: yes

- include_tasks: sound.yml

- name: Install "Dolphin" File Manager
  pacman:
    name: dolphin
    state: present
  become: yes

- name: Enable display resolution management and multiple monitors with "kscreen"
  pacman:
    name: kscreen
    state: present

- include_tasks: screen-sharing-kde.yml

- include_tasks: bluetooth.yml
