---
- name: Install power managing service
  pacman:
    name: powerdevil
    state: present

- name: Install integration with power profiles
  pacman:
    name: power-profiles-daemon
    state: present

- include_tasks: sound.yml

- name: Install "Dolphin" File Manager
  pacman:
    name: dolphin
    state: present

- include_tasks: screen-sharing.yml

- include_tasks: bluetooth.yml
