---
- name: Install packages
  pacman:
    name:
      - sway
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland
    state: present
  become: yes

- name: Install additional software
  pacman:
    name:
      - waybar
      - wofi
    state: present
  become: yes