---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xorg
    - sddm
    - plasma
  become: yes

- name: Enable display server and network
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - sddm
    - NetworkManager
  become: yes

- name: Change theme
  replace:
    path: /usr/lib/sddm/sddm.conf.d/default.conf
    regexp: ''
    replace: ''
  become: yes

- name: Install KDE applications
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - dolphin
    - dolphin-plugins
    - k3b
    - kalarm
    - kalendar
    - kdeconnect
    - kdegraphics-thumbnailers
    - kdenetwork-filesharing
    - kdesk-thumbnailers
    - kdf
    - kfind
    - kfloppy
    - kget
    - kgpg
    - khelpcenter
    - kleopatra
    - kmag
    - kmix
    - kmousetool
    - knotes
    - klourpaint
    - kompare
    - kontact
    - krgb
    - ksystemlog
    - ktimer
    - kwalletmanager
    - okular
    - partitionmanager
    - spectacle
    - svgpart
    - sweeper

- name: Install dependencies from different providers
  pacman: 
    name: "{{ item }}"
    state: present
  loop:
    - wireplumber
    - gnu-free-fonts
    - phonon-qt5-gstreamer
  become: yes

- name: Install power managing service and integration with power profiles
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - powerdevil
    - power-profiles-daemon
  become: yes

- name: Install applets
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - plasma-pa # audio
    - plasma-nm # network manager
  become: yes

- name: Install "pipewire-pulse" to avoid incompatibility between "pipewire" and "pulseaudio"
  pacman:
    name: pipewire-pulse
    state: present
  become: yes

- name: Uninstall  "pulseaudio" (dependency for "plasma-pa" and substituted by "pipewire-pulse")
  pacman:
    name: pulseaudio
    state: absent
    force: yes
  become: yes

- name: Enable display resolution management and multiple monitors with "kscreen"
  pacman:
    name: kscreen
    state: present

# Esto hace falta para pipewire + wayland para compartir pantalla
#- name: Install screen sharing WebRTC for KDE
#  pacman:
#    name: "{{ item }}"
#    state: present
#  loop:
#    - xdg-desktop-portal
#    - xdg-desktop-portal-kde
#  become: yes
