---
- name: Install KDE base packages
  pacman:
    name:
      - xorg
      - plasma
    state: present
  become: yes

- name: Install handler for audio/video in KDE
  pacman: 
    name: phonon-qt5-gstreamer
    state: present
  become: yes

- name: Install KDE applets
  pacman:
    name:
      - plasma-pa # audio
      - plasma-nm # network manager
    state: present
  become: yes

- name: Install KDE applications
  pacman:
    name:
      - dolphin
      - dolphin-plugins
      - k3b
      - kalarm
      - kalendar
      - kdeconnect
      - kdegraphics-thumbnailers
      - kdenetwork-filesharing
      - kdesdk-thumbnailers
      - kdf
      - kfind
      - kfloppy
      - kget
      - kgpg
      - khelpcenter
      - kleopatra
      - kmag
      - kmix
      - kmousetool
      - knotes
      - kolourpaint
      - kompare
      - kontact
      - krfb
      - kscreen # display resolution management and multiple monitors
      - ksystemlog
      - ktimer
      - kwalletmanager
    state: present
  become: yes

- name: Install power managing service and integration with power profiles
  pacman:
    name:
      - powerdevil
      - power-profiles-daemon
    state: present
  become: yes

- name: Install KDE front-end bluetooth manager
  pacman:
    name: bluedevil
    state: present
  become: yes