---
- name: Install Sway with Wayland
  include_tasks: sway.yml

- name: Install KDE Plasma with Xorg, as fallback
  include_tasks: kde.yml

- name: Uninstall conflicting dependencies
  pacman:
    name:
      - pulseaudio
      - pipewire-media-session
    state: absent
    force: yes
  become: yes

- name: Install "pipewire-pulse" to avoid incompatibility between "pipewire" and "pulseaudio"
  pacman:
    name: pipewire-pulse
    state: present
  become: yes

- name: Install screen sharing WebRTC for KDE
  pacman:
    name:
      - wireplumber
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
    state: present
  become: yes

- name: Install display manager
  pacman:
    name: sddm
    state: present
  become: yes

- name: Enable display server
  systemd:
    name: sddm
    state: started
    enabled: yes
  become: yes

# TODO: which regex
#- name: Change KDE Plasma theme
#  replace:
#    path: /usr/lib/sddm/sddm.conf.d/default.conf
#    regexp: ''
#    replace: 'breeze'
#  become: yes

