---
- name: Install "bluez" to provide Bluetooth protocol stack
  pacman:
    name: bluez
    state: present
  become: yes

- name: Check if Bluetooth generic drive is loaded
  modprobe:
    name: btusb
    state: present
  become: yes

- name: Enable "bluetooth.service"
  systemd:
    name: bluetooth
    state: started
    enabled: yes
  become: yes
