---
- name: Uninstall "dhcpcd" for incompatibility issues with "NetworkManager"
  pacman:
    name: dhcpcd
    state: absent
  become: yes

- name: Disable "dhcpcd" job in case enabled
  systemd:
    name: dhcpcd
    state: stopped
    enabled: no
  register: dhcpcd_service
  become: yes
  failed_when: dhcpcd_service is failed and 'Could not find the requested service' not in dhcpcd_service.msg

- name: Install network management tools
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - networkmanager
    - wireless_tools
    - wpa_supplicant
  become: yes

- name: Reload daemons just in case some cache file produces error
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable "NetworkManager" service
  systemd:
    name: NetworkManager
    state: started
    enabled: yes
  become: yes 

- name: Enable support for wireless connections with "wpa_supplicant"
  systemd:
    name: wpa_supplicant
    state: started
    enabled: yes
  become: yes

- name: Create a WiFi connection
  community.general.nmcli:
    type: wifi
    conn_name: "{{ item.ssid }}"
    ifname: "{{ ansible_default_ipv4.interface }}"
    ssid: "{{ item.ssid }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ item.pass }}"
    autoconnect: true
    state: present
  when: wifi is defined
  loop_control:
    label: "{{ item.ssid }}"
  become: yes
