---
- name: Install Emacs with Wayland support
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - include: yay.yml

    - name: Install emacs-pgtk-native-comp-git
      command: >-
        yay -S emacs-pgtk-native-comp-git --nodiffmenu --nocleanmenu
      become: no

    - debug:
        msg: "Installing Doom Emacs dependencies"

    - name: Install Git
      pacman:
        name: git
        state: present

    - name: Install ripgrep
      pacman:
        name: ripgrep
        state: present

    - name: Install fd to improve performance for many file indexing commands
      pacman:
        name: fd
        state: present

    - name: Download Doom Emacs from github
      git:
        repo: https://github.com/hlissner/doom-emacs
        dest: "~/.emacs.d"

    - name: Install Doom Emacs
      command: >-
        ~/.emacs.d/bin/doom install

    # TODO: Configure Doom Emacs
    # TODO: Install Doom Emacs modules dependencies
