---
- name: Install "lsd" new generation "ls"
  pacman:
    name: lsd
    state: present
  become: yes

- name: Uncomment aliases from ".zshrc"
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^#(alias l.*)'
    replace: '\1'
