---
- name: Install terminals
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - alacritty # TODO: check how it works in Sway
    - kitty # preferred by sway
  become: yes

- name: Install system monitor
  pacman:
    name: htop
    state: present
  become: yes

- name: Install terminal information tool
  pacman:
    name: neofetch
    state: present
  become: yes

- include_tasks: zsh.yml