---
- name: Install "Zsh"
  pacman:
    name: zsh
    state: present
  become: yes

- name: Change user default shell to "Zsh"
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes

- name: Check if OhMyZsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh

- name: Create temporary folder
  file:
    name: temp
    state: directory
  when: not ohmyzsh.stat.exists

- name: Download "Oh My Zsh" to customize "Zsh"
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: temp/
    mode: '744'
  when: not ohmyzsh.stat.exists

- name: Installation for "Oh My Zsh"
  script: temp/install.sh
  when: not ohmyzsh.stat.exists

- name: Recursively remove temporary directory
  file:
    path: temp
    state: absent
  when: not ohmyzsh.stat.exists

- name: Install "zsh-suggestions" as "Oh My Zsh" plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install "zsh-syntax-highlinghting" as "Oh My Zsh" plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Copy ".zshrc" configuration for Zsh, accounting for "OhMyZsh" plugins
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}"

# TODO: install Meslo Nerd Fonts from AUR

- name: Ensure ES locale exists in order to use powerlevel10k styles
  locale_gen:
    name: es_ES.UTF-8
    state: present
  become: yes

# TODO: install powerlevel10k from AUR

- name: Copy "powerlevel10k" configuration for Zsh aspect
  copy:
    src: .p10k.zsh
    dest: "{{ ansible_env.HOME }}"
