---
- name: Install partition manager
  pacman:
    name: partitionmanager
    state: present
  become: yes

- name: Install zip
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - zip
    - unzip
  become: yes

- name: Install password manager
  pacman:
    name: keepassxc
    state: present
  become: yes

- name: Install calculator
  pacman:
    name: qalculate-gtk
    state: present
  become: yes

- name: Install screenshot utility
  pacman:
    name: flameshot
    state: present
  become: yes

- name: Install image viewer
  pacman:
    name: gwenview
    state: present
  become: yes

- name: Install photo editor
  pacman:
    name: gimp
    state: present
  become: yes

- name: Install PDF reader
  pacman:
    name: okular
    state: present
  become: yes

- name: Install "Libreoffice", stable version
  pacman:
    name: libreoffice-still
    state: present
  become: yes

- name: Install font
  pacman:
    name: gnu-free-fonts
    state: present
  become: yes
