---
- name: Install "Vim"
  pacman: 
    name: vim
    state: present
  become: yes

- name: Copy Vim configuration
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0744
  become: yes

- name: Create folder for "vim-plug"
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory

- name: Download "vim-plug" to manage "Vim" plugins
  get_url: 
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0744
  become: yes

- name:
  debug:
    msg: 
      - "You need to manually install Vim plugins via vim-plug"
      - "To do so, run ':PlugInstall' in Vim"

- name:
  debug:
    msg: 
      - "In order to use Vim 'YouCompleteMe' you also need to compile it:"
      - "cd ~.vim/plugged/YouCompleteme"
      - "python3 install.py --<language>-completer --<language2>-completer"
      - "You may want to run this command after this playbook has finished with the 'dev' role"
