---
- name: Install Arduino IDE
  pacman:
    name:
      - arduino
      - arduino-cli
      - arduino-docs
      - arduino-avr-core
    state: present
  become: yes

- name: Add user to uucp group
  user:
    name: "{{ ansible_env.USER }}"
    groups: uucp
    append: yes
  become: yes

- name: Install "udev" to access serial port
  systemd:
    name: systemd-udevd
    state: started
    enabled: yes  
  become: yes
