---
- name: Install Docker
  pacman:
    name: docker
    state: present

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes

- name: Enable "docker.servicer"
  systemd:
    name: docker
    state: started
    enabled: yes

