---
- name: Install Docker
  pacman:
    name: docker
    state: present
  become: yes

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Enable "docker.servicer"
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
