- name: Install git version control tool
  pacman:
    name: git
    state: present
  become: yes

- include_tasks: arduino.yml

- include_tasks: aws.yml

- include_tasks: c.yml

- include_tasks: docker.yml

- include_tasks: python.yml

- include_tasks: terraform.yml
